import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import isValidURL from "../util/isValidURL";

export default function Home() {
  let [long_url, setLongURL] = useState("");
  return (
    <>
      <Head>
        <title>포이 (poi) / 손쉬운 URL 단축 서비스</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <h1 className={styles.title}>Poi.kr</h1>
        <h3 className={styles.desc}>외우기 쉬운 링크 단축 서비스</h3>
      </header>
      <main>
        <div className={styles.modal}>
          <h2 className={styles.title}>이용안내</h2>
        </div>
        <div
          className={styles.iptt}
          style={{
            padding: "18px 24px",
            display: "inline-block",
          }}
          onClick={() => {
            (
              document.querySelector(
                "#__next > main > div.Home_iptt__AUaUa > div > input"
              )! as HTMLInputElement
            ).focus();
          }}
        >
          <div
            style={{
              display: "block",
            }}
          >
            <div
              style={{
                display: "inline",
                position: "relative",
                top: "50%",
                transform: "translateY(-50%)",
                height: "24px",
                maxHeight: "24px",
              }}
              className="iconV"
            >
              <span
                className="material-symbols-outlined iconV"
                style={{
                  position: "absolute",
                  transform: "translateY(4px)",
                }}
              >
                link
              </span>
            </div>
            <input
              type="text"
              placeholder="URL을 입력해 주세요"
              value={long_url}
              style={{
                width: "100%",
                marginLeft: "28px",
                transform: "translateY(2px)",
              }}
              className={styles.ipt}
              onChange={(e) => {
                setLongURL(e.target.value);
              }}
            />
          </div>
        </div>
        <button
          style={{ display: "inline-block" }}
          className={styles.btn}
          onClick={() => {}}
          disabled={!isValidURL(long_url)}
        >
          단축하기
        </button>
      </main>
    </>
  );
}
